### ISSUE TITLE
默认的测试账号和密码是多少

### ISSUE THREAD

**Issue by jixiang-wang** [lyric777/Book-Management-System#2]

**Comment by lyric777** [comment]
这个我在readme文件里都说明了呀，账号：201801，密码：123456

**Comment by lpe234** [comment]
账号：201801，密码：123。可以直接连数据库看下，都是明文的。

这个代码里面问题比较多。好多东西没实现。比如

- 图书注销

另外。图书查询，默认展开列表比较方便，查询很费劲~

**Comment by lyric777** [comment]
哎呀，不知道回复楼上能不能看到。
图书注销这个问题，一开始老师发了一份很乱的需求文档，里面有这个功能，但却没有对这个功能的任何解释，所以这个就放在上面做了个空链接。

明文是因为我自己要改密码啊，所有用户的密码都是我自己在数据库端输入的，我自己输完也得告诉管理员不是，万一哪天谁忘了，也能告诉他（这不都是因为没有注册吗，需求文档里没有这个啊）

想加密就用werkzeug.security吧

最后，问题很多这个，我真的没什么好说的，我反正觉得没什么问题，自己也测试了很多，你觉得多就多吧
