### ISSUE TITLE
借阅卡到期是什么情况

### ISSUE THREAD

**Issue by Wangxinprogram** [lyric777/Book-Management-System#3]
为什么借阅卡的有效期会是1970-1-1，那样我无法检测借阅，还书功能。求大神给我讲讲。

**Comment by lyric777** [comment]
啊？我没懂，能再详细描述一下吗
或者微信联系我：Cyoung2_

**Comment by lyric777** [comment]
啊，我大概知道是怎么回事了，我在student表里设置的注册时间（enroll）和到期时间（valid）可能最后修改的时候忘了加三位了，数据库设计的13位，在原来的十位后面加三个0就好了
